export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const SORT_NONE = 'SORT_NONE';
export const SORT_TITLE_ASCENDING = 'SORT_TITLE_ASCENDING';
export const SORT_TITLE_DESCENDING = 'SORT_TITLE_DESCENDING';
export const SORT_ARTIST_ASCENDING = 'SORT_ARTIST_ASCENDING';
export const SORT_ARTIST_DESCENDING = 'SORT_ARTIST_DESCENDING';